### ISSUE TITLE
Styling: Symbols ...

### ISSUE THREAD

**Issue by fb71** [Mapzone/mapzone-atlas-plugin#10]
Styling:
  - GeoTools or OpenLayers?
  - Symbols for points (SVG, ...?)
  
## TODO

  - [ ] mehrere ScaleMappedValues (rule min/max Scale prüfen/aufteilen)
  - [x] FilterMappedColors  
  - [x] Text Halo
  - [x] Farbe und Opacity für SVGs einstellbar
  - [x] Schatten
  - [ ] Strich auf den Style 'gestrichelt' 
  - [ ] Transparent als Farbe in "Farbtabelle", und/oder "Aktiv" mit Wertliste, und/oder Feature-Filter
