### ISSUE TITLE
Desktop / Mobile

### ISSUE THREAD

**Issue by fb71** [Mapzone/mapzone-atlas-plugin#17]
Bedienung für mobile Geräte und Desktop-Browser

  - [x] Mobile: kein Header bei schmalen Displays
  - [x] #16 - Browser Back Button
  - [x] Panel Öffnen/Schließen: schneller, on top, Animation (https://icons8.com/preloaders/en/free)
  - [ ] Pan/Zoom mobil
  - [ ] Snackbar: manchmal zu spät; manchmal zu viel
  - [ ] keine Ränder bei mobil
  - [ ] Buttons für Panel-Navigation größer bei mobil (Abstand) ?
  - [ ] Title-Font bei mobil
  - [ ] #19 - Search Proposals mobil
  - [ ] (animierter) Zoom auf Suchergebnisse
  - [ ] Zoom auf ...
  - [x] #18 - gestylte Symbole in der Liste
  
  - ? Desktop: eigenes Panel für Objekteliste (im Branch task-17-DesktopMobile)
