### ISSUE TITLE
Click auf Feature

### ISSUE THREAD

**Issue by fb71** [Mapzone/mapzone-atlas-plugin#9]
Im Moment wird auf dem Server gerendert. Alle Ebenen können (müssen) also gestylt werden. Für die Darstellung im Atlas brauchen wir Images/Icons als Symbole (siehe #10).

Für Hover/Click in der Karte könnte entweder
  
  - zusätzlicher OpenLayers Vestor-Layer 
  - einheits Größe und Style für Atlas (roter Kreis bei Hover?)
  
## TODO

  - [x] click on feature in map
  - [x] center on list click
  - [x] hover on list click
  - [x] does not work on mapzone
